name: Build Art Gallery Page

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Optional: Custom commit message'
        required: false
        default: 'BOT: Rebuild art gallery page'

jobs:
  build-and-commit:
    name: Build and Commit Gallery
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: 1. Checkout Codebase
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Run the Gallery Builder Script
        id: build
        run: python build_gallery.py
      
      - name: 4. Commit the Updated Gallery HTML
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ github.event.inputs.commit_message }}
          # THIS IS THE FIX: The path now correctly points to the output file.
          file_pattern: "docs/art-gallery.html"
          commit_user_name: "Gallery Bot [Bot]"
          commit_user_email: "bot@bohemai.com"
          commit_author: "Gallery Bot <bot@bohemai.com>"
