# This workflow builds the art gallery HTML page automatically.
name: Build Art Gallery Page

on:
  # This allows you to run the workflow manually from the Actions tab.
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Optional: Custom commit message'
        required: false
        default: 'BOT: Rebuild art gallery page'

jobs:
  build-and-commit:
    name: Build and Commit Gallery
    runs-on: ubuntu-latest
    
    # Grant permissions for the job to write back to the repository.
    permissions:
      contents: write
      
    steps:
      - name: 1. Checkout Codebase
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Run the Gallery Builder Script
        id: build
        run: python build_gallery.py
      
      - name: 4. Commit the Updated Gallery HTML
        # This uses the same auto-commit action from your other bot.
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Use the message provided during dispatch, or the default.
          commit_message: ${{ github.event.inputs.commit_message }}
          # The full path to the file that the python script creates/updates.
          # Based on your screenshot, this is the correct path.
          file_pattern: "docs/art-gallery-images.html"
          commit_user_name: "Gallery Bot [Bot]"
          commit_user_email: "bot@bohemai.com"
          commit_author: "Gallery Bot <bot@bohemai.com>"
